# Generated by Django 4.2.13 on 2025-10-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Junta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizador', models.CharField(max_length=42)),
                ('num_participantes', models.PositiveIntegerField()),
                ('aporte', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
