# Generated by Django 4.2.13 on 2025-10-25 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dinero', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='junta',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='junta',
            old_name='aporte',
            new_name='cantidad_aporte',
        ),
        migrations.RenameField(
            model_name='junta',
            old_name='creada_en',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='junta',
            name='num_participantes',
        ),
        migrations.RemoveField(
            model_name='junta',
            name='organizador',
        ),
        migrations.AddField(
            model_name='junta',
            name='codigo',
            field=models.CharField(default='000000', editable=False, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='junta',
            name='direccion_organizador',
            field=models.CharField(default='Desconocida', max_length=100),
        ),
        migrations.AddField(
            model_name='junta',
            name='empezada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='junta',
            name='numero_participantes',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('pago_colateral', models.BooleanField(default=False)),
                ('pago_mensual', models.BooleanField(default=False)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('junta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dinero.junta')),
            ],
            options={
                'unique_together': {('junta', 'direccion')},
            },
        ),
    ]
