# Generated by Django 4.2.13 on 2025-10-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dinero', '0002_alter_junta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='junta',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Junta', 'verbose_name_plural': 'Juntas'},
        ),
        migrations.AlterModelOptions(
            name='participante',
            options={'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
    ]
