# Generated by Django 4.2.13 on 2025-10-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dinero', '0003_alter_junta_options_alter_participante_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='junta',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='participante',
            options={},
        ),
        migrations.AlterField(
            model_name='junta',
            name='codigo',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='junta',
            name='direccion_organizador',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='junta',
            name='numero_participantes',
            field=models.IntegerField(),
        ),
    ]
