# Generated by Django 4.2.13 on 2025-10-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dinero', '0004_alter_junta_options_alter_participante_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta',
            name='contract_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
